### PR TITLE
Theoretical implementation of custom types

### PR DESCRIPTION
**Pull request by TheToor**
_This is a theoretical implementation. Please do not merge. I opened this for discussion.
Read below. Code / implementation not final_

You already posted the idea of custom types to serialize -> #25
The idea is the same, the approach is other. I did it with an interface.

As you can see we have the same  RegisterCustomType code in server and client.
My idea would be to create a general serializer and reference that in both client and server. That way we have on location where all the serialization and deserialization happens and we don't double the code.
Also would be easier to maintain.

### CODE REVIEW

**Comment by Eastrall** [comment]
Since I have been working on the `NetClient` implementation this weekend, I have made some changes to the `NetPacket` implementation. I created an interface named `INetPacketStream` that represents an Ether.Network packet stream and his implmentation `NetPacketStream` (https://github.com/Eastrall/Ether.Network/blob/develop/src/Ether.Network/Packets/NetPacketStream.cs)
Every packet inherits from the `NetPacketStream`. It behaves just like the `NetPacketBase` class but we now use interfaces to increase maintainability.

About your implementation, I like the idea. If I understand correctly, during the `Initialize` process on `NetServer` or `NetClient` you need to do a `NetPacketBase.RegisterCustomType<T>()` ?

About this line : https://github.com/Eastrall/Ether.Network/pull/43/files#diff-fa8e3daa2aa900a661e14dccb208a731R57
Why you don't use the `INetSerializable` interface? It might be easier for you to call the `Serialize` and `Deserialize` methods :wink:

**Comment by Eastrall** [comment]
I have been thinking about this subject and instead of doing "type registration", why we do not simply extend the `INetPacketStream` interface to add a specific read/write method.

You already have the `INetSerializable` interface with both `Serialiaze` and `Deserialize` methods. Instead of taking a `BinaryReader/Writer` you can pass a `INetPacketStream` so you can do something like this:

```c#
class Vector3 : INetSerializable
{
    private float _x;
    private float _y;
    private float _z;

    void Serialize(INetPacketStream stream)
    {
        stream.Write(this._x);
        stream.Write(this._y);
        stream.Write(this._z);
    }

    void Deserialize(INetPacketStream stream)
    {
        this._x = stream.Read<float>();
        this._y = stream.Read<float>();
        this._z = stream.Read<float>();
    }
}
```

Then in the `NetPacketStream` implementation class you could call have `Write(INetSerializable)` method that will call the `Serialize` method of the object passed as parameter.
Tell me what do you think about this option :wink:

**Comment by TheToor** [comment]
The idea why `internal sealed class CustomType` exists was to add more constructors. So you have like
`RegisterCustomType<T>(Action<BinaryWriter, T> write, Func<BinaryReader, T> read)` to just easy add a serializer also to classes from other libraries.

The `INetPacketStream` looks fine to me. I did not pull your latest commit(s) as I was working on my fork. I have to review your changes first as you did change some things.

And yeah you have to call `RegisterCustomType` after the server / client startup. I want to extract that into one custom serializer class so we can reference it in server and client. Or I have to look through your latest changes if we can fit it into https://github.com/Eastrall/Ether.Network/blob/develop/src/Ether.Network/Packets/NetPacketMethods.cs but I don't think it really fits there. There is probably a scenario where you want the binary data without the packet itself. Would be nice to access that without the need to have a packet in my point of view.

**Comment by Eastrall** [comment]
I like the idea of `RegisterCustomType<T>(Action<BinaryWriter, T> write, Func<BinaryReader, T> read)` that can allow people to serialize classes from other libraries, good idea.

If we want to explore the two scenarios, the `RegisterCustomType<T>(...)` and the `INetSerializable` option, we can create an attribute that will tag the classes as "Serializable" and then automatically register the tag types at server/client initialization.

```c#
[NetSerializable]
public class Vector3 : INetSerializable
{
     void Serialize(INetPacketStream stream) { ... }
     void Deserialize(INetPacketStream stream) { ... }
}
```

**Comment by TheToor** [comment]
Sorry that I was inactive. Been busy at work.

Thats a good idea too. I will see if I can create the attribute `[NetSerializable]`.
I will also extend the RegisterCustomType and probably clean up some code.

Also seems like you were busy with Ether.Network so will update my code to latest build so we wouldn't have merge problems.

**Comment by Eastrall** [comment]
We will report this feature to next minor release (3.1.0).

**Pull request closed without merging**
