### PR TITLE
handle packets even for empty ones

### PR DESCRIPTION
**Pull request by Eastrall**
Handle packets even if they are empty.

### CODE REVIEW

**Comment by Yothri** [comment]
Okay to have the issue described here as well: This seems to work better, but not yet as expected. 
I can get ingame now with this, so packet exchange (proxying for my Packet Filter) works, but in the middle of the loading screen there comes a very huge packet (approx. +- 2000 bytes) and it seems to make problems there. The client gets ingame and that means there is already Initialization of Photon Server, Exchange of Encryption Keys and such done, so that worked, but then in GetPacketBuffer it says ObjectDisposedException, so something went wrong. Also, when changing BufferSizes the behaviour changes, I can not even get ingame with another BufferSize... I dont say the BufferSize is in any way related to that issue, but at least it affects the behaviour then (sure there are more iterations of receiving with smaller buffer size when having big packets).

**Comment by Eastrall** [comment]
Seems like the `Socket` has been disposed during the process... Can you give me the full process of what you do? for exemple:
- Create `NetClient`
- Connect()
- ...

**Comment by Yothri** [comment]
Here is the full project: https://github.com/Yothri/FLPH so you can see what happens.
You should be able to set it up also if you want I can tell you how. You need BlueStacks or an Android Phone, I can give you the APK of the game with gate host of your needs if you'd like to.

**Comment by Yothri** [comment]
This happens when the protocol is correct, just bytes are not received or sent or whatever fails here:
bla

**Comment by Yothri** [comment]
Not entirely sure, but I believe that, when HandleMessage() takes too long then this makes problems.
Why do I think that? When I connect the game to character creation, few packets are sent to display character, then if idle only ping packet is sent. That works flawlessly. I can let that run 5 hours and its still working. Now imagine that, I am currently printing the packets in Console Window. When marking something in console, the console thread is stopped right? That means, HandleMessage() is not being continued for the time of having console marked. When unmarking console then, it continues handlemessage, but then immediately the above exception occurs. So I guess its really when HandleMessage takes too much time, additional received data is already overwritten somewhere or something like that.

**Comment by Eastrall** [comment]
Maybe the fact that the `NetServer` is running on the main thread is the problem. I'll do some checks to run the server on another thread to see if that is really the problem.

**Comment by Eastrall** [comment]
From what I've read, it seems that the `HandleMessage` is called on the main thread, and this should cause the issues you are talking about. What I was thinking is to create a new `Task` that will process the received packets. They will be stored in a `BlockingCollection` just like we do for the sending process.

Since it's on another task, I think we should not have the problem anymore.

I'm merging this PR and opening a new one with the fix.

**Pull request merged**
