### PR TITLE
Fix for #40 and #41

### PR DESCRIPTION
**Pull request by TheToor**
This should add the following things:
#40 
#41

### CODE REVIEW

**Comment by TheToor** [comment]
The unit tests are broken in these commits as they don't yet have the new OnSocketError.
This is fixed in another commit in my fork.

(Ignore the first commit up there without the picture, something was fucked up with my local git)

**Comment by Eastrall** [comment]
Thanks for your Pull Request and help improving Ether.Network!
The tests are passing, but Codacy tells us that the IP `0.0.0.0` can be configurable. You can create a `private static readonly` field to store this IP address instead of comparing the hardcoded string 😉

**Comment by TheToor** [comment]
I moved it to a variable.
I don't think it is really needed as it only matters on this particular part.

**Comment by Eastrall** [comment]
All good! Let's merge!

**Comment by Yothri** [comment]
Fix for #40 is not yet included in the current Stable NuGet Package?
Because when I put 0.0.0.0 as Host it says its not allowed or sth. like that.

**Comment by Eastrall** [comment]
@Yothri the fix of issue #40 have not been released yet. It will be released with version 3.0.0.

**Pull request merged**
