### PR TITLE
Feature/net client config

### PR DESCRIPTION
**Pull request by Eastrall**
This PR adds the `NetClientConfiguration` class. It behaves the same as the `NetServerConfiguration`.

To configure a `NetClient`, you just need to call the `Configuration` property:

```c#
public class MyClient : NetClient
{
    public MyClient()
    {
        this.Configuration.Host = "127.0.0.1";
        this.Configuration.Port= 4444;
        this.Configuration.BufferSize= 1024;
    }
}
```

### CODE REVIEW

**Comment by johmarjac** [comment]
Ouhhh great! :D I was waiting for this. Thanks

**Comment by Eastrall** [comment]
@johmarjac this PR will now allow us to solve issue #57 and bring the `BlockingConnection` property to `NetClientConfiguration` to allow non-blocking connections on `NetClient.Connect()` call.

**Comment by johmarjac** [comment]
@Eastrall That would be great! :)

**Comment by Altiano** [comment]
There is no `BlockingConnection` in my version 3 ?

image

**Comment by Altiano** [comment]
Also there is not `TimeOut` property ?

**Comment by Eastrall** [comment]
@Altiano Version 3.0.0 doesn't have the `TimeOut` and `BlockingConnection` properties. They have been added after the V3.0.0 release. These properties will be included in version 3.1.X

**Comment by Altiano** [comment]
Oh I see... The latest on NuGet is `3.0.0`

**Comment by Eastrall** [comment]
Yes. V3.1.0 is not ready yet.

**Pull request merged**
